use portfolio_project;

-- Data cleaning-- 
 
select * from retail_sales
where ï»¿transactions_id is null;

select * from retail_sales
where sale_date is null;

select * from retail_sales
where 
      ï»¿transactions_id is null
      or
      sale_date is null
      or
      sale_time is null
      or
      gender is null
      or 
      category is null
      or 
      quantiy is null
      or
      cogs is null
      or 
      total_sale is null;
      
delete from retail_sales
WHERE
      ï»¿transactions_id is null
      or
      sale_date is null
      or
      sale_time is null
      or
      gender is null
      or 
      category is null
      or 
      quantiy is null
      or
      cogs is null
      or 
      total_sale is null;

-- Data Exploration --

 -- How many sales we have?--
 SELECT count(*) as total_sales FROM  retail_sales;
 
 -- how many unique customers we have ? --
 SELECT count(distinct customer_id ) as total_sales from retail_sales;

-- how many category we have --
select  distinct category from retail_sales;

-- Data Analysis & Business problems & Answers--
-- Write a sql query to retrive all columns for sales mode '2022-11-05'--
   Select * from retail_sales
   where sale_date = '2022-11-05';
   
--   Write a sql query to retrive all transaction where the category is 'clothing' 
--  and quantity sold is more than 10 on the month of Nov-2022 -- 
select *
	from retail_sales
	where category = 'clothing'
	and 
	sale_date >='2022-11-01' and sale_date < '2022-12-01'
	and
	quantiy >=4;

-- Write a SQL query to calculate the total sales (total_sales) for each category. --
SELECT category, sum(total_sale) as total_sales
	from retail_sales
	group by category;

-- Write a SQL query to find the average age of customer who purchased items from the 'beauty' category -- 
SELECT round(avg(age),2) as avg_age
	from retail_sales
	where category = 'beauty';

-- Write a SQL query to find all the transaction where the total_sale is greater than 1000--
select * from retail_sales
where total_sale > 1000;

-- Write a SQL query to find  the total number of transaction (transaction_id) made by each gender in each category.
SELECT category, gender,
	count(*)as total_trans
	from retail_sales
	group by category,gender;

-- Write a SQL query to calculate the average sales for each month. Find out best selling month in each year.
select 
	year,month,avg_sales
	from (
	select  year(sale_date) as year, month(sale_date) as month,
	avg(total_sale) as avg_sales,
	rank() over( partition by year(sale_date) order by (avg_sales) desc) as sales_rank 
	from retail_sales
	group by year,month) as t1
	where sales_rank=1;

-- Write a SQL query to find the top 5 customers based on the higest total sales
SELECT customer_id,sum(total_sale)as total_sales
	from retail_sales
	group by customer_id
	order by total_sale limit 5;

-- Write a SQL query to find the number of unique customer who purchased items from each category.
SELECT category,count( distinct customer_id) as count
	from retail_sales
	group by category;

-- write a SQL query to create each shift and number of orders (Example morning <=12, Afternoon =12&17, Evening = 17 )
with hourly_sales as 
(
SELECT *,
		case
			when hour (sale_time) < 12 then 'Morning'
			when hour  (sale_time) between 12 and 17 then 'Afternoon'
			ELSE 'Evening'
		END as shift
	from retail_sales
	)
	select
		shift,
		count(*) as total_orders
	from hourly_sales
	group by shift;

--  Extract all completed transactions under the 'Electronics' vertical where the gross 
--  transaction value exceeded $500, sorted from highest revenue to lowest.
SELECT  * from retail_sales
	where category ='Electronics' and total_sale > 500
	order by total_sale desc ;

-- Provide a high-level summary showing the total unique user base size and the absolute 
-- historical revenue generated by the platform.
SELECT count(distinct customer_id),count(ï»¿transactions_id),
	sum(total_sale)as gross_revenue
	from retail_sales;

-- Determine which business vertical dominates top-line revenue generation by summarizing total sales and volume, 
-- ranked from highest to lowest performance.

SELECT category,
	count(ï»¿transactions_id) as order_volume,
	sum(total_sale) as revenue_generated
	from retail_sales
	group by category;

-- Calculate the absolute gross profit dollars and the percentage gross profit margin
-- ($\text{GPM}$) for each product category to evaluate bottom-line efficiency.
SELECT
		category,
		sum(total_sale) as revenue,
		sum(cogs) as cost_of_goods,
		sum(total_sale) - sum(cogs) as gross_profit,
		ROUND((sum(total_sale) - sum(cogs))/ sum(total_sale)*100,2) as gross_profit_margin
	from retail_sales
	where total_sale IS NOT NULL AND cogs IS NOT NULL
	group by category
	order by gross_profit_margin desc;
	 